sudo: true
services:
  - docker
before_install:
  - docker build -t bmsa/api-gateway -f Dockerfile.dev .
script:
  - docker run bmsa/api-gateway npm run test-unit
after_success:
  - docker build -t $DOCKER_ID/buymystuffapp-api-gateway .
  - echo "$DOCKER_PASSWORD" | docker login -u "DOCKER_ID" --password-stdin
  - docker push $DOCKER_ID/buymystuffapp-api-gateway
branches:
  only:
    - master
